controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute

app_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: review_index
        permanent: false
