parameters:
    app.stopwords: '%kernel.project_dir%/config/stopwords'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            int $reviewsPerPage: '%env(int:REVIEWS_PER_PAGE)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
